// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brdzqhajkvehyornuofi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyZHpxaGFqa3ZlaHlvcm51b2ZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyNjA4NTcsImV4cCI6MjA4OTgzNjg1N30.zaKQLPiuw_nwzEUWIhkW3MqguiyL-1HlRlhN_30ulDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});