// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zeebjohmuvrcldedhtrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplZWJqb2htdXZyY2xkZWRodHJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0NjMyMjgsImV4cCI6MjA4ODAzOTIyOH0.P-Oq5RZIVtZX3pTRufhk9p7snVmTWXLGRx-VBdizB28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});